name = "termac-chat"
main = "index.js"
compatibility_date = "2024-01-01"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "termac-crm"
database_id = "3ea2282d-e655-477b-9d5e-560be2a1b40b"

[triggers]
crons = ["0 3 * * *"]
